Repository TaskSprint/task-sprint, pull requests merged in 2025-06, with the labels that each got.

#116 fix: fixed search bar
  resources/js/Components/Layout/SearchBar.tsx
Labels: bug, frontend

#118 fix: fixed task page
  resources/js/Pages/Task.tsx
Labels: bug, frontend

#119 fix: fixed task creation and some style fixes
  app/Http/Controllers/TaskCreationController.php
  app/Services/Models/TaskService.php
  resources/css/app.css
  resources/js/Components/ActionModal.tsx
  resources/js/Components/FavoriteEmployeesSM.tsx
  resources/js/Components/Shared/Input.tsx
  resources/js/Components/Shared/Textarea.tsx
  resources/js/Components/UploadFileModal.tsx
  resources/js/Pages/Task.tsx
  resources/js/Pages/TaskCreation.tsx
Labels: bug, backend, frontend

#121 Footer
  composer.lock
  lang/en/footer.php
  lang/en/sub-category.php
  lang/en/task-creation.php
  lang/ru/footer.php
  lang/ru/sub-category.php
  lang/ru/task-creation.php
  lang/uk/footer.php
  lang/uk/sub-category.php
  package-lock.json
  resources/js/Components/Layout/Footer.tsx
  resources/js/Components/Main/LastTasks/LastTaskCard.tsx
  resources/js/Components/Main/Roles.tsx
  resources/js/Components/ReviewsChip.tsx
  resources/js/Pages/EmploeesPage.tsx
  resources/js/Pages/TaskCreation.tsx
  routes/web.php
Labels: 🖌️ auto prettify

#124 feat: added page titles
  lang/en/task-creation.php
  lang/ru/task-creation.php
  lang/uk/task-creation.php
  resources/js/Pages/Profile/Archive.tsx
  resources/js/Pages/Profile/BecomeEmployee.tsx
  resources/js/Pages/Profile/EmployeeInfo.tsx
  resources/js/Pages/Profile/Favorite.tsx
  resources/js/Pages/Profile/GeneralInfo.tsx
  resources/js/Pages/Profile/InProgress.tsx
  resources/js/Pages/Profile/NewTask.tsx
  resources/js/Pages/SubCategory.tsx
  resources/js/Pages/Task.tsx
  resources/js/Pages/TaskCreation.tsx
Labels: frontend
