Repository TaskSprint/task-sprint, pull requests merged in 2025-05, with the labels that each got.

#76 Glassmorphism
  lang/en/auth/login.php
  lang/ru/auth/login.php
  lang/uk/auth/login.php
  package-lock.json
  package.json
  resources/js/Components/CategoryTestCard.tsx
  resources/js/Components/Layout/Footer.tsx
  resources/js/Components/Layout/Navigation.tsx
  resources/js/Components/Layout/SearchBar.tsx
  resources/js/Components/Main/Categories.tsx
  resources/js/Components/Main/Info.tsx
  resources/js/Components/Main/LastTasks/LastTasks.tsx
  resources/js/Components/Main/Roles.tsx
  resources/js/Components/Main/Support.tsx
  resources/js/Components/Main/Title.tsx
  resources/js/Components/SafeHtml.tsx
  resources/js/Components/Shared/Button.tsx
  resources/js/Layouts/UserLayout.tsx
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Auth/Register.tsx
  resources/js/Pages/CategoryTest.tsx
  resources/js/Pages/Profile/Favorite.tsx
  resources/js/Pages/Profile/InProgress.tsx
  resources/js/Pages/Profile/NewTask.tsx
  resources/js/providers.tsx
  resources/js/types/global.d.ts
  tailwind.config.js
Labels: frontend

#79 Update user info
  .env.example
  .gitattributes
  app/Filament/Resources/UserResource.php
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Models/User.php
  app/Services/Models/UserService.php
  app/Traits/Models/PolicyChecks.php
  composer.json
  composer.lock
  config/user.php
  database/factories/UserFactory.php
  database/migrations/2025_05_01_143138_update_user_info.php
  database/seeders/UsersSeeder.php
  lang/en/users.php
  lang/en/validation.php
  lang/ru/users.php
  lang/ru/validation.php
  lang/uk/users.php
  lang/uk/validation.php
  public/js/filament/forms/components/markdown-editor.js
Labels: backend

#81 Navigation authenticated state
  app/Http/Middleware/HandleInertiaRequests.php
  composer.lock
  database/migrations/2025_05_01_143138_update_user_info.php
  package-lock.json
  resources/js/Components/Layout/Footer.tsx
  resources/js/Components/Layout/LanguageSwitcher.tsx
  resources/js/Components/Layout/Navigation.tsx
  resources/js/Layouts/AppLayout.tsx
  resources/js/Layouts/UserLayout.tsx
  resources/js/Pages/Profile/Favorite.tsx
  resources/js/hooks/useRouter.ts
  resources/js/types/index.d.ts
  resources/js/types/models/user.d.ts
  routes/web.php
Labels: backend, frontend

#90 White background input fixes
  resources/css/app.css
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Auth/Register.tsx
Labels: frontend

#91 Main colorize
  composer.lock
  package-lock.json
  package.json
  resources/js/Components/Layout/LanguageSwitcher.tsx
  resources/js/Components/Layout/Navigation.tsx
  resources/js/Components/Layout/SearchBar.tsx
  resources/js/Components/Main/LastTasks/LastTasks.tsx
Labels: 🖌️ auto prettify, frontend

#92 Employee review popup
  lang/en/employee-review.php
  lang/ru/employee-review.php
  lang/uk/employee-review.php
  resources/js/Components/EmployeeReviewPopup.tsx
  resources/js/Components/MarkStarRating.tsx
  resources/js/Components/StarRating.tsx
Labels: component, frontend

#69 task-creation-page
  hero.ts
  lang/en/task-creation.php
  lang/ru/task-creation.php
  lang/uk/task-creation.php
  package-lock.json
  package.json
  resources/css/app.css
  resources/js/Components/DateSelector.tsx
  resources/js/Components/FavoriteEmployeesSM.tsx
  resources/js/Components/Layout/Navigation.tsx
  resources/js/Components/LoadFile.tsx
  resources/js/Components/Main/Roles.tsx
  resources/js/Components/Main/Support.tsx
  resources/js/Components/SafeHtml.tsx
  resources/js/Components/Shared/Button.tsx
  resources/js/Components/Shared/Carousel.tsx
  resources/js/Pages/Main.tsx
  resources/js/Pages/TaskCreation.tsx
  routes/web.php
  tailwind.config.js
Labels: 🖌️ auto prettify, page, frontend

#98 Fixed inputs and some other fixes
  composer.lock
  lang/en/profile/update.php
  lang/ru/profile/update.php
  lang/uk/profile/update.php
  package-lock.json
  package.json
  resources/js/Components/ApplicationLogo.tsx
  resources/js/Components/Shared/Input.tsx
  resources/js/Layouts/AuthenticatedLayout.tsx
  resources/js/Layouts/GuestLayout.tsx
  resources/js/Pages/Auth/ConfirmPassword.tsx
  resources/js/Pages/Auth/ForgotPassword.tsx
  resources/js/Pages/Auth/Login.tsx
  resources/js/Pages/Auth/Register.tsx
  resources/js/Pages/Auth/ResetPassword.tsx
  resources/js/Pages/Auth/VerifyEmail.tsx
  resources/js/Pages/Dashboard.tsx
  resources/js/Pages/Profile/Edit.tsx
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.tsx
Labels: bug, frontend

#101 Fixed user layout
  composer.lock
  resources/js/Layouts/DashboardLayout.tsx
  resources/js/Layouts/UserLayout.tsx
  resources/js/Pages/Profile/Archive.tsx
  resources/js/Pages/Profile/Favorite.tsx
  resources/js/Pages/Profile/InProgress.tsx
  resources/js/Pages/Profile/NewTask.tsx
Labels: bug, frontend

#104 fix: fixed verification error and added toast
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/Auth/VerifyEmailController.php
  lang/en/main.php
  lang/ru/main.php
  lang/uk/main.php
  resources/js/Pages/Main.tsx
  resources/js/providers.tsx
Labels: bug, enhancement, backend, frontend

#108 fix: added nullish check
  package-lock.json
  resources/js/Layouts/ProfileLayout.tsx
Labels: bug, frontend

#109 fix: removed route copy
  routes/web.php
Labels: bug, frontend
